Repository Zeroes-Heroes/ChatAPI, pull requests merged in 2024-05, with the labels that each got.

#6 [CHAT-17] On register, add check if the phone already exists
  ChatAPI.Application/UseCases/Abstractions/IUserRepository.cs
  ChatAPI.Application/UseCases/Implementations/UserService.cs
  ChatAPI.Persistence/Repositories/UserRepository.cs
  ChatAPI.WebAPI/Controllers/AuthorizationController.cs
Labels: bug

#8 [CHAT-4] Login
  ChatAPI.Application/DTOs/Authorization/UserLoginDTO.cs
  ChatAPI.Application/DTOs/Authorization/UserLoginResponseDTO.cs
  ChatAPI.Application/UseCases/Abstractions/IUserRepository.cs
  ChatAPI.Application/UseCases/Abstractions/IUserService.cs
  ChatAPI.Application/UseCases/Implementations/UserService.cs
  ChatAPI.Persistence/Repositories/UserRepository.cs
  ChatAPI.WebAPI/Controllers/AuthorizationController.cs
Labels: enhancement

#10 [CHAT-24] Verify sms code
  ChatAPI.Application/UseCases/Abstractions/IUserRepository.cs
  ChatAPI.Application/UseCases/Implementations/UserService.cs
  ChatAPI.Domain/Entities/User.cs
  ChatAPI.Persistence/Repositories/UserRepository.cs
Labels: bug, good first issue

#9 [CHAT-7] Friend requests
  ChatAPI.Application/ChatAPI.Application.csproj
  ChatAPI.Application/Hubs/BaseHub.cs
  ChatAPI.Application/UseCases/Abstractions/IFriendshipRepository.cs
  ChatAPI.Application/UseCases/Abstractions/IFriendshipService.cs
  ChatAPI.Application/UseCases/Abstractions/ITokenService.cs
  ChatAPI.Application/UseCases/Abstractions/IUserRepository.cs
  ChatAPI.Application/UseCases/Abstractions/IUserService.cs
  ChatAPI.Application/UseCases/Abstractions/Repositories/IBaseRepository.cs
  ChatAPI.Application/UseCases/Abstractions/Repositories/IFriendshipRepository.cs
  ChatAPI.Application/UseCases/Abstractions/Repositories/IUserRepository.cs
  ChatAPI.Application/UseCases/Abstractions/Services/IFriendshipService.cs
  ChatAPI.Application/UseCases/Abstractions/Services/ITokenService.cs
  ChatAPI.Application/UseCases/Abstractions/Services/IUserService.cs
  ChatAPI.Application/UseCases/Implementations/FriendshipService.cs
  ChatAPI.Application/UseCases/Implementations/UserService.cs
  ChatAPI.Domain/Entities/User.cs
  ChatAPI.Domain/LiveConnections/DTOs/FriendRequestDTO.cs
  ChatAPI.Domain/LiveConnections/LiveEvents.cs
  ChatAPI.Infrastructure/ChatAPI.Infrastructure.csproj
  ChatAPI.Persistence/ChatAPI.Persistence.csproj
  ChatAPI.Persistence/Configurations/FriendshipConfiguration.cs
  ChatAPI.Persistence/Database/AppDbContext.cs
  ChatAPI.Persistence/Migrations/20240428214021_InitialCreate.Designer.cs
  ChatAPI.Persistence/Migrations/20240502211142_AddUserLoginCodesTable.cs
  ChatAPI.Persistence/Migrations/20240503191406_MapUserLoginCodeToUserDevice.Designer.cs
  ChatAPI.Persistence/Migrations/20240503191406_MapUserLoginCodeToUserDevice.cs
  ChatAPI.Persistence/Migrations/20240504224303_InitialCreate.Designer.cs
  ChatAPI.Persistence/Migrations/20240504224303_InitialCreate.cs
  ChatAPI.Persistence/Migrations/AppDbContextModelSnapshot.cs
  ChatAPI.Persistence/Repositories/FriendshipRepository.cs
  ChatAPI.Persistence/Repositories/UserRepository.cs
  ChatAPI.WebAPI/ChatAPI.WebAPI.csproj
  ChatAPI.WebAPI/Controllers/AuthorizationController.cs
  ChatAPI.WebAPI/Controllers/FriendsController.cs
  ChatAPI.WebAPI/Extensions/ServiceCollectionExtension.cs
  ChatAPI.WebAPI/Hubs/ChatHub.cs
  ChatAPI.WebAPI/Program.cs
  ChatAPI.WebAPI/Services/Authorization/TokenService.cs
Labels: enhancement
